### ISSUE TITLE
Gateway API - Ensure UTF8 (unicode) data sent from SOLR

### ISSUE THREAD

**Issue by datadavev** [datadavev/DwC_views#11]
This ticket is a reminder that output from SOLR should be showing up as UTF-8 encoded text. 

Django does everything in unicode internally, so it _may_ be necessary to ensure all content being read from SOLR is appropriately converted to unicode, and that all outgoing text (e.g. transformed, added to templates, in JSON strings, etc) is appropriately converted to UTF-8.

Should probably have a couple of unit tests to cover this.

**Comment by coreyo** [comment]
The SOLR client api already has utf-8 encoding specified throughout.  As it turns out, the default JSON encoder/decoder objects in python (i.e. json and simplejson) use utf-8 by default.  I went ahead and specified "encoder='utf-8'" in all of the encoders, but this is redundant.

We should proceed with some unit tests.

**Comment by datadavev** [comment]
Added a simple unit test to verify output is encoded as expected and that content is not being doubly encoded by the gateway.

Closing this issue - it appears everything is working as expected.
