### ISSUE TITLE
Actions when clicking on a record in the table view

### ISSUE THREAD

**Issue by datadavev** [datadavev/DwC_views#28]
- Clicking on the ID field should show a complete view of the content held in the record

There may be some actions appropriate for other fields, not yet determined - so the click action needs to be configurable per field.

**Comment by coreyo** [comment]
Clicking on ID field implementation working, but hardcoded.

TODO: specify optional callback function for each field to be called when the user clicks on that field.  This may be difficult to implement since the initial declaration might not have a handle on the objects needed in the callback function.

**Comment by datadavev** [comment]
Functionality to keep in mind - there should ideally be mechanisms to select an individual record in the different views. 
- Clicking on some row property in the multi-record view (e.g. ID or whole row)
- Clicking on a pin in the map view

Both should be able to invoke the same operation (e.g. show the record details), but the actual operation invoked should be settable, and may potentially be set to a different operation for each view.

**Comment by coreyo** [comment]
This functionality has been superseded by ticket #35

Implemented a row-click functionality with this default action as well as an optional per-field value click.
