### ISSUE TITLE
Implement gateway infrastructure for retrieving content from a SOLR index of Darwin Core records

### ISSUE THREAD

**Issue by datadavev** [datadavev/DwC_views#7]
Implement gateway infrastructure for retrieving content from a SOLR index of
Darwin Core records

All output from the gateway API services should be encoded in JSON using the
UTF8 character set.

Methods mapping from the gateway API to the SOLR API will be implemented using this infrastructure.

**Comment by coreyo** [comment]
Initial implementation is done.  All functions work almost as described in the Gateway API.

ToDo:
- fields caching
- error/exception handling
- urlencode/decode handling
- enforcing unicode format
- source type and host information should be configurable via settings file (instead of hard-coded)

**Comment by coreyo** [comment]
Gateway API Implementation is now completely functional.  The following ToDo items have been assigned their own individual tickets.  I have linked the descriptions to their corresponding tickets below.  Closing this ticket if there are no objections.

ToDo:
- fields caching (ticket #14)
- error/exception handling (ticket #16)
- urlencode/decode handling (ticket #17)
- enforcing unicode format (ticket #15)
- source type and host information should be configurable via settings file (instead of hard-coded) (ticket #18)
